ldap:
  uri: ldap://192.168.1.2:389/dc=company,dc=com
  user: uid=admin,ou=adminstrators,dc=company,dc=com
  password: secret

kk

security:
  sessions: NEVER

logging:
  level:
    org.springframework:
      security: INFO
      session: INFO

